name: Generate God-Level Assets

on:
  schedule:
    - cron: "0 */24 * * *" # Runs every 24 hours
  workflow_dispatch: # Allows manual click to run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D City & Snake
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # GENERATE SNAKE ANIMATION
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # GENERATE 3D CITY (Corrected Author: yoshi389111)
      - name: Generate 3D City
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # PUSH ASSETS TO BRANCH
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
